### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by Pillar1989** [Seeed-Studio/seeed-linux-openwrt#2]
* [ ]  ~~Seeed MT7628 board support openwrt 19.07~~
* [x]  Support CM4
* [x]  Support Odyssey X86
* [ ]  ~~interface usage documents~~
* [ ]   ~~Add some useful plugins~~
  -  * [ ] ~~support [JerryScript](https://github.com/jerryscript-project/jerryscript) GUI , refer to HarmonyOS.~~
  -  * [ ] ~~support [LVGL](https://github.com/lvgl/lvgl), easy python GUI.~~
* [x] release binary image

**Comment by Pillar1989** [comment]
* [ ]  Seeed MT7628 board support openwrt 19.07

**Comment by BKPepe** [comment]
>  luci-app-netdata

What should the package do, or what are the requirements for the package? I hope it should not be like this:
https://github.com/openwrt/luci/pull/5443

Basically, luci-app-netdata is not needed at all.

**Comment by lakshanthad** [comment]
The original intention was to include it to monitor system resources. Is there a problem if we include it?

**Comment by BKPepe** [comment]
But you don't need luci-app for that, right? You can use ``netdata``, which is available to install and you will monitor system resources on http://IPaddress:19999

**Comment by lakshanthad** [comment]
You are correct. How would you suggest adding `netdata` to the OpenWrt build?

**Comment by BKPepe** [comment]
If you are using [OpenWrt packages feed](https://github.com/openwrt/packages), you don't need to do anything since it is there.

**Comment by lakshanthad** [comment]
I have tried it with netdata enabled here:
https://github.com/Seeed-Studio/seeed-linux-openwrt/blob/magic/configs/rpi_cm4_defconfig#L1625

And it works on http://IPaddress:19999 as you mentioned.

**Comment by LynnL4** [comment]
Close it, then discuss it here https://github.com/Seeed-Studio/seeed-linux-openwrt/issues/38
